### ISSUE TITLE
Updating this repo to .NET 6

### ISSUE THREAD

**Issue by cmaneu** [microsoft/vscode-remote-try-dotnetcore#30]
Hey Team, 
Following a discussion with @codemillmatt and @bamurtaugh, I have created an updated sample, targeting .NET 6. However, we are wondering if we should rename the current repo (`vscode-remote-try-dotnetcore` would be renamed `vscode-remote-try-dotnet`). As @codemillmatt said:
> The issue with using dotnetcore in the template's name is that .NET Core does not exist as a platform any longer (end of support in December 2022). Now it's .NET, nothing else.

We came up with two options: 

1. **Archive that repo, create a new one called "dotnet", and update all docs**: This will require to update a lot of places (both doc and in-product). This might be hard to do. We can still mention the new repo in the readme before archiving the repo, but it's one more click.
2. **Rename that repo to `vscode-remote-try-dotnet` and let GitHub handle redirects**

**Comment by bamurtaugh** [comment]
Thanks for opening!

When you say "Archive that repo," is that repo https://github.com/microsoft/vscode-remote-try-dotnet? Since we haven't directed users to it, I'd recommend deleting it and potentially we rename this repo to `vscode-remote-try-dotnet`

For others viewing this discussing: my recommendation has been to update this repo’s content and naming and not introduce a new repo. GitHub will handle directs so we don't break existing users or references, and this way we avoid fracturing the community be presenting multiple .NET sample repos.

**Comment by cmaneu** [comment]
I've updated my first comment for clarity. After a good night of sleep, I do think your proposal is the best course of action. On top of that, I can create a git tag on the current version and mention it in the updated readme. Doing so, if people are still using .NET Core, they would be able to easily find the current (.NET Core) sample.

**Comment by bamurtaugh** [comment]
Sounds good, thanks! In that case, please feel free to open a PR with the changes you had in mind, and we can change the repo name at the same time we merge the PR. And whenever you're comfortable with it, you may delete https://github.com/microsoft/vscode-remote-try-dotnet, so that the repos don't conflict. :)

**Comment by cmaneu** [comment]
@bamurtaugh I've: 
- [x] Deleted https://github.com/microsoft/vscode-remote-try-dotnet
- [x] Pushed my code to my own fork and opened #31 

The only missing piece is HTTPS support. I'll work on it later this week. We can merge the first PR and I'll open a second one for HTTPS, or wait for everything to merge it, as you prefer.
